version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: '/wasm/app/wasm/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      cargo:
        patterns:
          - '*'

  - package-ecosystem: npm
    directories:
      - '/cloudwatch-rum/pages/'
      - '/cloudwatch-rum/infra/'
      - '/cloudwatch-rum/infra/function/'
      - '/kuma-ui-example/'
      - '/github-auth-ssg/frontend/'
      - '/github-auth-ssg/frontend/cdk/'
      - '/github-auth-ssg/backend/'
      - '/graphql-msw/frontend/cdk/'
      - '/graphql-msw/frontend/'
      - '/graphql-msw/backend/'
      - '/mui-github-oauth/frontend/'
      - '/mui-github-oauth/frontend/cdk/'
      - '/mui-github-oauth/backend/'
      - '/next-amplified/'
      - '/next-gsap-example/'
      - '/next-i18n/app/''
      - '/next-i18n/infra/''
      - '/next-i18n/infra/function/''
      - '/next-ts-amplify-hosting-template/'
      - '/next-ts-amplify-hosting-template/cdk/'
      - '/next-ts-biome-example/'
      - '/next-zustand-example/'
      - '/nextjs-dynamic-routing-app/app/'
      - '/sticky-example/'
      - '/vnc-example/'
      - '/wasm/'
      - '/wasm/app/'
      - '/wasm/infra/'
      - '/with-preact/'
      - '/with-rspack/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      npm:
        patterns:
          - '*'
