packages:
  - ./
  - ./cloudwatch-rum/pages
  - ./cloudwatch-rum/infra
  - ./cloudwatch-rum/infra/function
  - ./github-auth-ssg/frontend
  - ./github-auth-ssg/frontend/cdk
  - ./github-auth-ssg/backend
  - ./graphql-msw/frontend/cdk
  - ./graphql-msw/frontend
  - ./graphql-msw/backend
  - ./kuma-ui-example
  - ./next-amplified
  - ./next-gsap-example
  - ./next-i18n/app
  - ./next-i18n/infra
  - ./next-i18n/infra/function
  - ./next-ts-biome-example
  - ./next-zustand-example
  - ./nextjs-dynamic-routing-app/app
  - ./sticky-example
  - '!./with-beta/**'
  - ./wasm
  - ./wasm/app
  - ./wasm/infra
  - '!./with-preact/**'

auto-install-peers: true

enablePrePostScripts: true

legacy-peer-deps: true

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@biomejs/biome'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - next-plugin-preact
  - sharp
  - unrs-resolver

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  immutable@<4.3.8: '>=4.3.8'

strictPeerDependencies: false
