packages:
  - ./kuma-ui-example
  - ./next-amplified
  - ./next-gsap-example
  - ./next-redux-toolkit-example
  - ./next-ts-amplify-hosting-template
  - ./next-ts-amplify-hosting-template/cdk
  - ./next-ts-biome-example
  - ./next-ts-radixui-example
  - ./next-zustand-example
  - ./nextjs-dynamic-routing-app/app
  - ./sticky-example
  - ./vanilla-extract-example
  - ./vnc-example
  - ./with-bata
  - ./with-preact

enable-pre-post-scripts: true

auto-install-peers: true

strict-peer-dependencies: false

overrides:
  postcss@<8.4.31: '>=8.4.31'
  nth-check@<2.0.1: '>=2.0.1'
  esbuild@<=0.24.2: '>=0.25.0'
