packages:
  - ./
  - ./cloudwatch-rum/pages
  - ./cloudwatch-rum/infra
  - ./cloudwatch-rum/infra/function
  - ./github-auth-ssg/frontend
  - ./github-auth-ssg/frontend/cdk
  - ./github-auth-ssg/backend
  - ./mui-github-oauth/frontend/cdk
  - ./mui-github-oauth/frontend
  - ./mui-github-oauth/backend
  - ./kuma-ui-example
  - ./next-amplified
  - ./next-gsap-example
  - ./next-redux-toolkit-example
  - ./next-ts-amplify-hosting-template
  - ./next-ts-amplify-hosting-template/cdk
  - ./next-ts-biome-example
  - ./next-ts-radixui-example
  - ./next-zustand-example
  - ./nextjs-dynamic-routing-app/app
  - ./sticky-example
  - ./vanilla-extract-example
  - ./vnc-example
  - '!./with-beta/**'
  - ./with-preact
  - ./with-rspack

enable-pre-post-scripts: true
legacy-peer-deps: true
auto-install-peers: true
strict-peer-dependencies: false

overrides:
  postcss@<8.4.31: '>=8.4.31'
  nth-check@<2.0.1: '>=2.0.1'
  esbuild@<=0.24.2: '>=0.25.0'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - next-plugin-preact
  - sharp
