packages:
  - ./
  - ./cloudwatch-rum/pages
  - ./cloudwatch-rum/infra
  - ./cloudwatch-rum/infra/function
  - ./github-auth-ssg/frontend
  - ./github-auth-ssg/frontend/cdk
  - ./github-auth-ssg/backend
  - ./graphql-msw/frontend/cdk
  - ./graphql-msw/frontend
  - ./graphql-msw/backend
  - ./mui-github-oauth/frontend/cdk
  - ./mui-github-oauth/frontend
  - ./mui-github-oauth/backend
  - ./kuma-ui-example
  - ./next-amplified
  - ./next-gsap-example
  - ./next-i18n/app
  - ./next-i18n/infra
  - ./next-i18n/infra/function
  - ./next-ts-amplify-hosting-template
  - ./next-ts-amplify-hosting-template/cdk
  - ./next-ts-biome-example
  - ./next-zustand-example
  - ./nextjs-dynamic-routing-app/app
  - ./sticky-example
  - ./vnc-example
  - '!./with-beta/**'
  - ./wasm
  - ./wasm/app
  - ./wasm/infra
  - ./with-preact
  - ./with-rspack

auto-install-peers: true

enablePrePostScripts: true

legacy-peer-deps: true

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@biomejs/biome'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - aws-sdk
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - next-plugin-preact
  - sharp
  - unrs-resolver

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@next/eslint-plugin-next@<15.5.0': '>=15.5.0'
  '@types/react-dom@<19.1.7': '>=19.1.7'
  '@types/react@<19.1.10': '>=19.1.10'
  esbuild@<=0.24.2: '>=0.25.0'
  eslint-config-next@<15.5.0: '>=15.5.0'
  next@<15.5.0: '>=15.5.0'
  nth-check@<2.0.1: '>=2.0.1'
  postcss@<8.4.31: '>=8.4.31'
  react-dom@<19.1.1: '>=19.1.1'
  react@<19.1.1: '>=19.1.1'
  tailwindcss@<4.0.0: '>=4.0.0'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
  '@typescript-eslint/typescript-estree@<8.40.0': '>=8.40.0'

strictPeerDependencies: false
