packages:
  - ./
  - ./cloudwatch-rum/pages
  - ./cloudwatch-rum/infra
  - ./cloudwatch-rum/infra/function
  - ./github-auth-ssg/frontend
  - ./github-auth-ssg/frontend/cdk
  - ./github-auth-ssg/backend
  - ./graphql-msw/frontend/cdk
  - ./graphql-msw/frontend
  - ./graphql-msw/backend
  - ./kuma-ui-example
  - ./next-amplified
  - ./next-gsap-example
  - ./next-i18n/app
  - ./next-i18n/infra
  - ./next-i18n/infra/function
  - ./next-ts-biome-example
  - ./next-zustand-example
  - ./nextjs-dynamic-routing-app/app
  - ./sticky-example
  - '!./with-beta/**'
  - ./wasm
  - ./wasm/app
  - ./wasm/infra
  - '!./with-preact/**'

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - 'lodash@4.18.1'
  - vite@7.3.2 || 8.0.7
  - '@vitest/*'
  - vitest@4.1.3
  - '@esbuild/*'
  - esbuild@0.28.0

  - react@19.2.5
  - react-dom@19.2.5

  - '@mui/material-nextjs@7.3.10 || 9.0.0'
  - '@mui/material@7.3.10 || 9.0.0'
  - '@mui/system@7.3.10 || 9.0.0'
  - '@mui/icons-material@7.3.10 || 9.0.0'
  - '@mui/styled-engine@7.3.10 || 9.0.0'
  - '@mui/utils@7.3.10 || 9.0.0'
  - '@mui/core-downloads-tracker@7.3.10 || 9.0.0'
  - '@mui/private-theming@7.3.10 || 9.0.0'
  - '@mui/types@7.3.10 || 9.0.0'
  - '@mui/x-date-pickers@7.3.10 || 9.0.0'
  - '@mui/x-internals@7.3.10 || 9.0.0'

  - 'follow-redirects@1.16.0'

overrides:
  '@types/node': ^24
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3'
  chokidar: '>=5'
  esbuild@<=0.24.2: '>=0.25.0'
  eslint-import-resolver-typescript: '>=4'
  flatted@<=3.4.1: '>=3.4.2'
  follow-redirects@<=1.15.11: '>=1.16.0'
  graphql: '>=16'
  h3@<=1.15.4: '>=1.15.5'
  handlebars@>=4.0.0 <4.7.9: '>=4.7.9'
  handlebars@>=4.0.0 <=4.7.8: '>=4.7.9'
  handlebars@>=4.6.0 <=4.7.8: '>=4.7.9'
  immutable@<3.8.3: '>=3.8.3'
  lodash-es@<=4.17.23: '>=4.18.0'
  lodash-es@>=4.0.0 <=4.17.23: '>=4.18.0'
  lodash@<=4.17.23: '>=4.18.0'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.23: '>=4.18.0'
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=10.0.0 <10.2.3: '>=10.2.3'
  semver: '>=7'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  ua-parser-js: '>=2'
  vite@>=8.0.0 <=8.0.4: '>=8.0.5'

trustPolicy: no-downgrade
trustPolicyExclude:
  - reselect@5.1.1
