packages:
  - ./
  - ./cloudwatch-rum/pages
  - ./cloudwatch-rum/infra
  - ./cloudwatch-rum/infra/function
  - ./github-auth-ssg/frontend
  - ./github-auth-ssg/frontend/cdk
  - ./github-auth-ssg/backend
  - ./graphql-msw/frontend/cdk
  - ./graphql-msw/frontend
  - ./graphql-msw/backend
  - ./kuma-ui-example
  - ./next-amplified
  - ./next-gsap-example
  - ./next-i18n/app
  - ./next-i18n/infra
  - ./next-i18n/infra/function
  - ./next-ts-amplify-hosting-template
  - ./next-ts-amplify-hosting-template/cdk
  - ./next-ts-biome-example
  - ./next-zustand-example
  - ./nextjs-dynamic-routing-app/app
  - ./sticky-example
  - ./vnc-example
  - '!./with-beta/**'
  - ./wasm
  - ./wasm/app
  - ./wasm/infra
  - '!./with-preact/**'

auto-install-peers: true

enablePrePostScripts: true

legacy-peer-deps: true

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@biomejs/biome'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - aws-sdk
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - next-plugin-preact
  - sharp
  - unrs-resolver

overrides:
  '@eslint/compat': ^2.0.0
  '@graphql-codegen/cli': ^6.1.0
  '@graphql-codegen/client-preset': ^5.2.2
  '@graphql-codegen/typescript-msw': ^3.0.1
  '@graphql-codegen/typescript-react-apollo': ^4.3.4
  '@graphql-eslint/eslint-plugin': ^4.4.0
  '@graphql-typed-document-node/core': ^3.2.0
  '@next/bundle-analyzer@<=16.0.0': ^16.0.0
  '@next/eslint-plugin-next@<=16.0.0': ^16.0.0
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  '@storybook/addon-docs': ^10.1.10
  '@storybook/addon-links': ^10.1.10
  '@storybook/addon-onboarding': ^10.1.10
  '@storybook/addon-styling-webpack': ^3.0.0
  '@storybook/addon-themes': ^10.1.10
  '@storybook/nextjs': ^10.1.10
  '@types/node': ^24.10.4
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@typescript-eslint/typescript-estree@<8.40.0': ^8.40.0
  diff@<8.0.3: '>=8.0.3'
  esbuild: ^0.27.2
  esbuild@<=0.24.2: '>=0.25.0'
  eslint-config-next@<=15.5.0: ^16.0.0
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-storybook: ^10.1.10
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  next@=16.0.0: ^16.0.0
  nth-check@<2.0.1: '>=2.0.1'
  postcss@<8.4.31: '>=8.4.31'
  react-dom@<=19.2.0: ^19.2.0
  react@<=19.2.0: ^19.2.0
  storybook: ^10.1.10
  tailwindcss@<4.0.0: ^4.0.0
  uuid: ^13.0.0
  vite@>=7.1.0 <=7.1.4: ^7.1.5
  webpack-dev-server@<=5.2.0: '>=5.2.1'

strictPeerDependencies: false
