packages:
  - ./

auto-install-peers: true

enablePrePostScripts: true

legacy-peer-deps: true

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@biomejs/biome'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - aws-sdk
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - next-plugin-preact
  - sharp
  - unrs-resolver

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@next/bundle-analyzer@<=16.0.0': ^16.0.0
  '@next/eslint-plugin-next@<=16.0.0': ^16.0.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@typescript-eslint/typescript-estree@<8.40.0': '>=8.40.0'
  esbuild@<=0.24.2: ^0.27.0
  eslint-config-next@<=15.5.0: ^16.0.0
  eslint@<9.26.0: '>=9.26.0'
  next@=16.0.0: ^16.0.0
  nth-check@<2.0.1: '>=2.0.1'
  postcss@<8.4.31: '>=8.4.31'
  react-dom@<=19.2.0: npm:@preact/compat@^18.3.1
  react@<=19.2.0: npm:@preact/compat@^18.3.1
  tailwindcss@<4.0.0: '>=4.0.0'
  vite@>=7.1.0 <=7.1.4: ^7.1.5
  webpack-dev-server@<=5.2.0: '>=5.2.1'
  webpack@>=5.49.0 <5.104.0: '>=5.104.0'
  webpack@>=5.49.0 <=5.104.0: '>=5.104.1'

strictPeerDependencies: false
